#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Feb 27, 2019 02:01:55 AM CET  platform: Linux

import sys
from Loi import LoiProb as loi
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import FAS_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    FAS_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    FAS_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def uniforme(self):
      try:
       nbr=int(self.Entry1.get())      
       a= int(self.Unif_A.get())
       b= int(self.Unif_B.get())       
       loi.unif(self,a,b,nbr)
      except : print('Error')

    def poiss(self) :
     try:
      nbr=int(self.Entry1.get()) 
      lamda=int(self.poiss_lamda.get())
      loi.poiss(self,lamda,nbr)
     except : print('Error')

    def exp (self):
     try:
      nbr=int(self.Entry1.get()) 
      lamda=int(self.exp_lamda.get())
      loi.exp(self,lamda,nbr)
     except : print('Error')
      
    def gamma(self):
      try:        
       nbr=int(self.Entry1.get())    
       n= int(self.gamma_n.get())
       lamda=int(self.gamma_lamda.get())
       loi.gamma(self,n,lamda,nbr)
      except : print('Error')
      
    def normal(self):
      try: 
       nbr=int(self.Entry1.get())          
       moy=int(self.normal_moy.get())
       var= int(self.normal_var.get())
       loi.normal(self,moy,var,nbr)
      except : print('Error')

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {DejaVu Serif} -size 14 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("1238x771+116+38")
        top.title("Simulation des Nombres Aléatoires")
        top.configure(background="#ffffff")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.008, rely=0.013, relheight=0.979
                , relwidth=0.981)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(width=1215)

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.025, rely=0.066, relheight=0.404
                , relwidth=0.292)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(width=355)

        self.Button2 = tk.Button(self.Frame2)
        self.Button2.place(relx=0.085, rely=0.197, height=211, width=291)
        self.Button2.configure(activebackground="#f9f9f9")
        self._img1 = tk.PhotoImage(file="./Uniform.png")
        self.Button2.configure(image=self._img1)
        self.Button2.configure(state='active')
        self.Button2.configure(text='''Button''')
        self.Button2.configure(command=self.uniforme)

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.338, rely=0.902, height=21, width=115)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Uniforme [a,b]''')

        self.Unif_A = tk.Entry(self.Frame2)
        self.Unif_A.place(relx=0.197, rely=0.098,height=23, relwidth=0.13)
        self.Unif_A.configure(background="white")
        self.Unif_A.configure(font="TkFixedFont")
        self.Unif_A.configure(selectbackground="#c4c4c4")

        self.Unif_B = tk.Entry(self.Frame2)
        self.Unif_B.place(relx=0.648, rely=0.098,height=23, relwidth=0.13)
        self.Unif_B.configure(background="white")
        self.Unif_B.configure(font="TkFixedFont")
        self.Unif_B.configure(selectbackground="#c4c4c4")

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.113, rely=0.098, height=21, width=12)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''a''')

        self.Label2_1 = tk.Label(self.Frame2)
        self.Label2_1.place(relx=0.507, rely=0.098, height=21, width=49)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(text='''b''')

        self.Frame2_5 = tk.Frame(self.Frame1)
        self.Frame2_5.place(relx=0.337, rely=0.066, relheight=0.404
                , relwidth=0.292)
        self.Frame2_5.configure(relief='groove')
        self.Frame2_5.configure(borderwidth="2")
        self.Frame2_5.configure(relief='groove')
        self.Frame2_5.configure(width=355)

        self.exp_lamda = tk.Entry(self.Frame2_5)
        self.exp_lamda.place(relx=0.535, rely=0.098,height=23, relwidth=0.13)
        self.exp_lamda.configure(background="white")
        self.exp_lamda.configure(font="TkFixedFont")
        self.exp_lamda.configure(selectbackground="#c4c4c4")

        self.Label2_4 = tk.Label(self.Frame2_5)
        self.Label2_4.place(relx=0.324, rely=0.098, height=21, width=49)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(text='''lamda''')

        self.Button2_1 = tk.Button(self.Frame2_5)
        self.Button2_1.place(relx=0.085, rely=0.197, height=211, width=291)
        self.Button2_1.configure(activebackground="#f9f9f9")
        self._img2 = tk.PhotoImage(file="./Exponential.png")
        self.Button2_1.configure(image=self._img2)
        self.Button2_1.configure(text='''Button''')
        self.Button2_1.configure(command=self.exp)

        self.Label4_2 = tk.Label(self.Frame2_5)
        self.Label4_2.place(relx=0.31, rely=0.902, height=21, width=149)
        self.Label4_2.configure(activebackground="#f9f9f9")
        self.Label4_2.configure(text='''Expenonsiel (lamda)''')

        self.Frame2_6 = tk.Frame(self.Frame1)
        self.Frame2_6.place(relx=0.667, rely=0.066, relheight=0.404
                , relwidth=0.292)
        self.Frame2_6.configure(relief='groove')
        self.Frame2_6.configure(borderwidth="2")
        self.Frame2_6.configure(relief='groove')
        self.Frame2_6.configure(width=355)

        self.poiss_lamda = tk.Entry(self.Frame2_6)
        self.poiss_lamda.place(relx=0.521, rely=0.098,height=23, relwidth=0.13)
        self.poiss_lamda.configure(background="white")
        self.poiss_lamda.configure(font="TkFixedFont")
        self.poiss_lamda.configure(selectbackground="#c4c4c4")

        self.Label2_5 = tk.Label(self.Frame2_6)
        self.Label2_5.place(relx=0.324, rely=0.098, height=21, width=49)
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(text='''lamda''')

        self.Button2_2 = tk.Button(self.Frame2_6)
        self.Button2_2.place(relx=0.099, rely=0.197, height=211, width=291)
        self.Button2_2.configure(activebackground="#f9f9f9")
        self._img3 = tk.PhotoImage(file="./Poisson.png")
        self.Button2_2.configure(image=self._img3)
        self.Button2_2.configure(text='''Button''')
        self.Button2_2.configure(command=self.poiss)

        self.Label4 = tk.Label(self.Frame2_6)
        self.Label4.place(relx=0.366, rely=0.918, height=21, width=109)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''Poisson (lamda)''')

        self.Frame2_3 = tk.Frame(self.Frame1)
        self.Frame2_3.place(relx=0.025, rely=0.503, relheight=0.404
                , relwidth=0.292)
        self.Frame2_3.configure(relief='groove')
        self.Frame2_3.configure(borderwidth="2")
        self.Frame2_3.configure(relief='groove')
        self.Frame2_3.configure(width=355)

        self.gamma_n = tk.Entry(self.Frame2_3)
        self.gamma_n.place(relx=0.197, rely=0.098,height=23, relwidth=0.13)
        self.gamma_n.configure(background="white")
        self.gamma_n.configure(font="TkFixedFont")
        self.gamma_n.configure(selectbackground="#c4c4c4")

        self.gamma_lamda = tk.Entry(self.Frame2_3)
        self.gamma_lamda.place(relx=0.648, rely=0.098,height=23, relwidth=0.13)
        self.gamma_lamda.configure(background="white")
        self.gamma_lamda.configure(font="TkFixedFont")
        self.gamma_lamda.configure(selectbackground="#c4c4c4")

        self.Label1_3 = tk.Label(self.Frame2_3)
        self.Label1_3.place(relx=0.113, rely=0.098, height=21, width=12)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(text='''n''')

        self.Label2_6 = tk.Label(self.Frame2_3)
        self.Label2_6.place(relx=0.507, rely=0.098, height=21, width=49)
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(text='''lamda''')

        self.Button2_3 = tk.Button(self.Frame2_3)
        self.Button2_3.place(relx=0.085, rely=0.197, height=211, width=291)
        self.Button2_3.configure(activebackground="#f9f9f9")
        self._img4 = tk.PhotoImage(file="./Gamma.png")
        self.Button2_3.configure(image=self._img4)
        self.Button2_3.configure(text='''Button''')
        self.Button2_3.configure(command=self.gamma)

        self.Label5 = tk.Label(self.Frame2_3)
        self.Label5.place(relx=0.324, rely=0.902, height=21, width=126)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Gamma(n,lamda)''')

        self.Frame2_4 = tk.Frame(self.Frame1)
        self.Frame2_4.place(relx=0.337, rely=0.503, relheight=0.404
                , relwidth=0.292)
        self.Frame2_4.configure(relief='groove')
        self.Frame2_4.configure(borderwidth="2")
        self.Frame2_4.configure(relief='groove')
        self.Frame2_4.configure(width=355)

        self.normal_moy = tk.Entry(self.Frame2_4)
        self.normal_moy.place(relx=0.211, rely=0.098,height=23, relwidth=0.13)
        self.normal_moy.configure(background="white")
        self.normal_moy.configure(font="TkFixedFont")
        self.normal_moy.configure(selectbackground="#c4c4c4")

        self.normal_var = tk.Entry(self.Frame2_4)
        self.normal_var.place(relx=0.648, rely=0.098,height=23, relwidth=0.13)
        self.normal_var.configure(background="white")
        self.normal_var.configure(font="TkFixedFont")
        self.normal_var.configure(selectbackground="#c4c4c4")

        self.Label1_4 = tk.Label(self.Frame2_4)
        self.Label1_4.place(relx=0.113, rely=0.098, height=21, width=33)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(text='''moy''')

        self.Label2_7 = tk.Label(self.Frame2_4)
        self.Label2_7.place(relx=0.507, rely=0.098, height=21, width=49)
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(text='''var''')

        self.Label5_5 = tk.Label(self.Frame2_4)
        self.Label5_5.place(relx=0.324, rely=0.902, height=21, width=126)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(text='''Normle(moy,var)''')

        self.Button2_5 = tk.Button(self.Frame2_4)
        self.Button2_5.place(relx=0.099, rely=0.197, height=211, width=281)
        self.Button2_5.configure(activebackground="#f9f9f9")
        self._img5 = tk.PhotoImage(file="./normal.png")
        self.Button2_5.configure(image=self._img5)
        self.Button2_5.configure(text='''Button''')
        self.Button2_5.configure(command=self.normal)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.568, rely=0.013,height=23, relwidth=0.071)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(width=86)
       

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.37, rely=0.013, height=27, width=215)
        self.Label3.configure(activeforeground="#dd0d30")
        self.Label3.configure(font=font9)
        self.Label3.configure(highlightcolor="#db0025")
        self.Label3.configure(text='''Nombre des Variables''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





